# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/arttuleh/koulu/ot-harjoitustyo/src/gui/components/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sudoku(object):
    def setupUi(self, Sudoku):
        Sudoku.setObjectName("Sudoku")
        Sudoku.resize(918, 600)
        Sudoku.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Sudoku)
        self.centralwidget.setObjectName("centralwidget")
        self.set_difficulty = QtWidgets.QPushButton(self.centralwidget)
        self.set_difficulty.setGeometry(QtCore.QRect(70, 480, 201, 51))
        self.set_difficulty.setObjectName("set_difficulty")
        self.open_sudoku = QtWidgets.QPushButton(self.centralwidget)
        self.open_sudoku.setGeometry(QtCore.QRect(300, 480, 201, 51))
        self.open_sudoku.setObjectName("open_sudoku")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(200, 60, 511, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.check_sudoku = QtWidgets.QPushButton(self.centralwidget)
        self.check_sudoku.setGeometry(QtCore.QRect(520, 480, 191, 51))
        self.check_sudoku.setObjectName("check_sudoku")
        self.diff_label = QtWidgets.QLabel(self.centralwidget)
        self.diff_label.setGeometry(QtCore.QRect(10, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.diff_label.setFont(font)
        self.diff_label.setObjectName("diff_label")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(10, 110, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.help_button = QtWidgets.QPushButton(self.centralwidget)
        self.help_button.setGeometry(QtCore.QRect(10, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.help_button.setFont(font)
        self.help_button.setObjectName("help_button")
        Sudoku.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Sudoku)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 22))
        self.menubar.setObjectName("menubar")
        Sudoku.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Sudoku)
        self.statusbar.setObjectName("statusbar")
        Sudoku.setStatusBar(self.statusbar)

        self.retranslateUi(Sudoku)
        QtCore.QMetaObject.connectSlotsByName(Sudoku)

    def retranslateUi(self, Sudoku):
        _translate = QtCore.QCoreApplication.translate
        Sudoku.setWindowTitle(_translate("Sudoku", "MainWindow"))
        self.set_difficulty.setText(_translate("Sudoku", "Choose difficulty"))
        self.open_sudoku.setText(_translate("Sudoku", "Open a sudoku"))
        self.label.setText(_translate("Sudoku", "Sudoku"))
        self.check_sudoku.setText(_translate("Sudoku", "Check the sudoku"))
        self.diff_label.setText(_translate("Sudoku", "Difficulty: Choose"))
        self.status_label.setText(_translate("Sudoku", "Status: Start a sudoku"))
        self.help_button.setText(_translate("Sudoku", "Help"))
